name: disCoreEmbedded
version: '1.1'
main: space.merrioverse.disCoreEmbedded.DisCoreEmbedded
api-version: '1.21'
authors: [ Merriolium ]
description: Embedded style text for DisCoreBot
dependencies:
  server:
    DisCoreBot:
      load: BEFORE
      required: true
      join-classpath: true
